sudo: required

language: go

services:
        - docker

go:
        - master

after_success:
        - docker build -t yogiibot .
        - docker tag authservice "penutty/yogiibot:$TRAVIS_COMMIT"
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push "penutty/yogiibot:$TRAVIS_COMMIT"
